driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-6.0.8
  - name: debian-7.2.0
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[redis::server]
      - recipe[redis::client]
      # - recipe[minitest-handler]
